language: generic
sudo: required ## We need superuser permission when setting up docker
## line 3 4 is saying that Travis, we need a copy of docker ready to go
services:
  - docker

## Before the tests are ran
before_install:
  ## You can use any tag name like MYIMAGE, but it is a convention to use <docker-username>/<name>
  - docker build -t ishaanrawat/docker-react -f Dockerfile.dev .

## The commands that actually need to be executed to run the test suite
scripts:
  ## -- --coverage to make sure that npm run test command exits when it's done.
  - docker run ishaanrawat/docker-react npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "<Name-of-your-app-as-entered-when-creating-in-beanstalk>"
#   env: "<Name-of-env>"
#   bucket_name: "Something like elasticbeanstalk-us-west-2-2131231231"
#   bucket_path: "<Name-of-your-app-as-entered-when-creating-in-beanstalk>"
#   on:
#     branch: master
#   ##Check video named Automated deployment for the key generation
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
